### 1. Fazer Login (Clique em Send Request aqui em cima)
POST http://localhost:51213/api/auth/login
Content-Type: application/json

{
  "email": "daniel.dc697@gmail.com",
  "senha": "costa8991"
}

### 2. Criar Comentário (Substitua o TOKEN e o ID_DO_POST)
POST http://localhost:51213/api/posts/69a738e25b52f522961ac272/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZTQwODg5MDBmMmRiMzliZjdkMzVlOSIsImVtYWlsIjoiZGFuaWVsLmRjNjk3QGdtYWlsLmNvbSIsImlhdCI6MTc3MjY3MzU5MCwiZXhwIjoxNzczMjc4MzkwfQ.WCNHu2Mm802Gs3vVqmKCVJ3uoaOI79dS9Uz2ZF26_rI

{
  "text": "Comentário de teste via REST Client!"
}

### 3. Listar Comentários
GET http://localhost:51213/api/posts/COLE_O_ID_AQUI/comments